import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";

import "./globals.css";
import { ThemeProvider } from "@/lib/theme-provider";
import Navbar from "@/templates/navbar/navbar";

import { getServerSession } from "next-auth";
// import connectDB from "@/lib/connectDB";
import User from "@/models/user";

import { authOptions } from "@/auth-options";

import { SessionProvider } from "next-auth/react";
import SessionProviderComp from "@/lib/session-provider";
import TanstackProvider from "@/lib/tanstack-provider";

import { getPrefLangCookie } from "@/utilities/getPrefLangCookie"
import GoogleTranslateProvider from "@/utilities/google-translate";
import Footer from "@/templates/footer";


const vazir = Vazirmatn({ subsets: ["arabic"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  // await connectDB()
  // const session = await getServerSession(authOptions);
  // const user = await User?.findOne({ email: session?.user?.email });


  const prefLangCookie = getPrefLangCookie();

  return (
    <html lang="fa" >
      <body className={vazir.className}>
        <GoogleTranslateProvider>

          <TanstackProvider>
            <SessionProviderComp>

              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <Navbar
                  // prefLangCookie={prefLangCookie}
                  // userInfo={user}

                  // userInfo={JSON.parse(JSON.stringify(user))}
                />
                {children}

                <Footer />
              </ThemeProvider>
            </SessionProviderComp>
          </TanstackProvider>
        </GoogleTranslateProvider>
      </body>
    </html >
  );
}






